name: Deploy to VPS

on:
  push:
    branches:
      - main   # Ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@147.93.8.61 << 'EOF'
            cd system-menu-web || exit
            git pull origin main || exit  # Faz pull das últimas alterações
            npm install || exit          # Instala dependências
            npm run build || exit         # Gera a build do Next.js
            pm2 start npm --name "nextjs-app" -- start || pm2 restart "nextjs-app"
          EOF
